### ISSUE TITLE
使用Memorystream进行Excel反序列化抛出异常

### ISSUE THREAD

**Issue by wwHwo** [mini-software/MiniExcel#648]
### Excel Type

- [x] XLSX

### Upload Excel File
[text.xlsx](https://github.com/user-attachments/files/16596441/text.xlsx)
### MiniExcel Version
		<PackageReference Include="MiniExcel" Version="1.31.2" />
### Description
 public async Task<(bool flag, string message)> UpdateByExcel(IFormFile file)
    {
        try
        {
            var dtoes = file.OpenReadStream().Query<Dto>().ToList();
}
执行上述代码时,会抛出如下异常:
System.IO.InvalidDataException: Offset to Central Directory cannot be held in an Int64.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at MiniExcelLibs.Zip.MiniExcelZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at MiniExcelLibs.Zip.ExcelOpenXmlZip..ctor(Stream fileStream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at MiniExcelLibs.OpenXml.ExcelOpenXmlSheetReader..ctor(Stream stream, IConfiguration configuration)
   at MiniExcelLibs.ExcelReaderFactory.GetProvider(Stream stream, ExcelType excelType, IConfiguration configuration)
   at MiniExcelLibs.MiniExcel.Query[T](Stream stream, String sheetName, ExcelType excelType, String startCell, IConfiguration configuration)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by michelebastione** [comment]
@wwHwo I have been unable to reproduce the issue. The following minimal api snippet works as expected:

```cs
app.MapPost("/upload", (IFormFile file) => { using var stream = file.OpenReadStream(); return MiniExcel.Query(stream).ToList(); });
```

If you're still experiencing the problem it might be due to the encoding with which you are uploading it. Feel free to comment providing more details. Until then I will mark this issue as closed.
